In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
import math
import statistics
import seaborn as sns
from IPython.display import display
!pip install pingouin
!pip install researchpy
import researchpy
import pingouin as pg   
%matplotlib inline

Requirement already satisfied: pingouin in ./opt/anaconda3/lib/python3.8/site-packages (0.3.10)
Requirement already satisfied: pandas-flavor>=0.1.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.2.0)
Requirement already satisfied: scipy>=1.3 in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (1.5.2)
Requirement already satisfied: outdated in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.2.0)
Requirement already satisfied: seaborn>=0.9.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.11.0)
Requirement already satisfied: tabulate in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.8.9)
Requirement already satisfied: statsmodels>=0.10.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.12.0)
Requirement already satisfied: matplotlib>=3.0.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (3.3.2)
Requirement already satisfied: numpy>=1.15 in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (1.19.2)
Requirement already satisfied: pandas>=0.24 in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (1.1.3)
Requirement already satisfied: scikit-learn in ./opt/anaconda3/lib/python3.8/site-packages (from pingouin) (0.23.2)
Requirement already satisfied: xarray in ./opt/anaconda3/lib/python3.8/site-packages (from pandas-flavor>=0.1.2->pingouin) (0.16.2)
Requirement already satisfied: requests in ./opt/anaconda3/lib/python3.8/site-packages (from outdated->pingouin) (2.24.0)
Requirement already satisfied: littleutils in ./opt/anaconda3/lib/python3.8/site-packages (from outdated->pingouin) (0.2.2)
Requirement already satisfied: patsy>=0.5 in ./opt/anaconda3/lib/python3.8/site-packages (from statsmodels>=0.10.0->pingouin) (0.5.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (8.0.1)
Requirement already satisfied: python-dateutil>=2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (1.3.0)
Requirement already satisfied: certifi>=2020.06.20 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (2020.6.20)
Requirement already satisfied: cycler>=0.10 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib>=3.0.2->pingouin) (0.10.0)
Requirement already satisfied: pytz>=2017.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24->pingouin) (2020.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./opt/anaconda3/lib/python3.8/site-packages (from scikit-learn->pingouin) (2.1.0)
Requirement already satisfied: joblib>=0.11 in ./opt/anaconda3/lib/python3.8/site-packages (from scikit-learn->pingouin) (0.17.0)
Requirement already satisfied: setuptools>=38.4 in ./opt/anaconda3/lib/python3.8/site-packages (from xarray->pandas-flavor>=0.1.2->pingouin) (50.3.1.post20201107)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->outdated->pingouin) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->outdated->pingouin) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./opt/anaconda3/lib/python3.8/site-packages (from requests->outdated->pingouin) (3.0.4)
Requirement already satisfied: six in ./opt/anaconda3/lib/python3.8/site-packages (from patsy>=0.5->statsmodels>=0.10.0->pingouin) (1.15.0)
Collecting researchpy
  Downloading researchpy-0.2.3-py3-none-any.whl (10 kB)
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.8/site-packages (from researchpy) (1.19.2)
Requirement already satisfied: scipy in ./opt/anaconda3/lib/python3.8/site-packages (from researchpy) (1.5.2)
Requirement already satisfied: pandas in ./opt/anaconda3/lib/python3.8/site-packages (from researchpy) (1.1.3)
Requirement already satisfied: statsmodels in ./opt/anaconda3/lib/python3.8/site-packages (from researchpy) (0.12.0)
Requirement already satisfied: python-dateutil>=2.7.3 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas->researchpy) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas->researchpy) (2020.1)
Requirement already satisfied: patsy>=0.5 in ./opt/anaconda3/lib/python3.8/site-packages (from statsmodels->researchpy) (0.5.1)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas->researchpy) (1.15.0)
Installing collected packages: researchpy
Successfully installed researchpy-0.2.3

In [6]:
df_train = pd.read_csv("Titanic_train.csv")
print(df_train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [8]:
#Q1：透過數值法計算 Age 和 Survived 是否有相關性？
contTable = pd.crosstab(df_train['Age'], df_train['Survived'])
contTable

Survived  0  1
Age
0.42      0  1
0.67      0  1
0.75      0  2
0.83      0  2
0.92      0  1
...      .. ..
70.00     2  0
70.50     1  0
71.00     2  0
74.00     1  0
80.00     0  1

[88 rows x 2 columns]

In [9]:
df = min(contTable.shape[0], contTable.shape[1]) - 1
df

1

In [10]:
crosstab, res = researchpy.crosstab(df_train['Age'], df_train['Survived'], test='chi-square')
print(res.loc[2,'results'])

0.3819

In [11]:
def judgment_CramerV(df,V):
    if df == 1:
        if V < 0.10:
            qual = 'negligible'
        elif V < 0.30:
            qual = 'small'
        elif V < 0.50:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 2:
        if V < 0.07:
            qual = 'negligible'
        elif V < 0.21:
            qual = 'small'
        elif V < 0.35:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 3:
        if V < 0.06:
            qual = 'negligible'
        elif V < 0.17:
            qual = 'small'
        elif V < 0.29:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 4:
        if V < 0.05:
            qual = 'negligible'
        elif V < 0.15:
            qual = 'small'
        elif V < 0.25:
            qual = 'medium'
        else:
            qual = 'large'
    else:
        if V < 0.05:
            qual = 'negligible'
        elif V < 0.13:
            qual = 'small'
        elif V < 0.22:
            qual = 'medium'
        else:
            qual = 'large'
    return(qual)

judgment_CramerV(df,res.loc[2,'results'])

'medium'

In [12]:
#Q2:透過數值法計算 Sex 和 Survived 是否有相關性?
contTable2 = pd.crosstab(df_train['Sex'], df_train['Survived'])
contTable2

Survived    0    1
Sex
female     81  233
male      468  109

In [14]:
df2 = min(contTable2.shape[0], contTable2.shape[1]) - 1
df2

1

In [15]:
crosstab, res = researchpy.crosstab(df_train['Sex'], df_train['Survived'], test='chi-square')
print(res.loc[2,'results'])

0.5434

In [16]:
def judgment_CramerV(df,V):
    if df == 1:
        if V < 0.10:
            qual = 'negligible'
        elif V < 0.30:
            qual = 'small'
        elif V < 0.50:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 2:
        if V < 0.07:
            qual = 'negligible'
        elif V < 0.21:
            qual = 'small'
        elif V < 0.35:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 3:
        if V < 0.06:
            qual = 'negligible'
        elif V < 0.17:
            qual = 'small'
        elif V < 0.29:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 4:
        if V < 0.05:
            qual = 'negligible'
        elif V < 0.15:
            qual = 'small'
        elif V < 0.25:
            qual = 'medium'
        else:
            qual = 'large'
    else:
        if V < 0.05:
            qual = 'negligible'
        elif V < 0.13:
            qual = 'small'
        elif V < 0.22:
            qual = 'medium'
        else:
            qual = 'large'
    return(qual)

judgment_CramerV(df,res.loc[2,'results'])

'large'

In [17]:
#Q3: 透過數值法計算 Age 和 Fare 是否有相關性?
contTable3 = pd.crosstab(df_train['Age'], df_train['Fare'])
contTable3

Fare,0.0000,4.0125,5.0000,6.2375,6.4375,6.4500,6.4958,6.7500,6.9750,7.0458,...,151.5500,153.4625,164.8667,211.3375,211.5000,227.5250,247.5208,262.3750,263.0000,512.3292
Age,,,,,,,,,,,,,,,,,,,,,
0.42,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.67,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.75,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.83,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.92,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70.00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
70.50,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
71.00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74.00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
80.00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df3 = min(contTable3.shape[0], contTable3.shape[1]) - 1
df3

87

In [19]:
crosstab, res = researchpy.crosstab(df_train['Age'], df_train['Fare'], test='chi-square')
print(res.loc[2,'results'])

0.5705

In [20]:
def judgment_CramerV(df,V):
    if df == 1:
        if V < 0.10:
            qual = 'negligible'
        elif V < 0.30:
            qual = 'small'
        elif V < 0.50:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 2:
        if V < 0.07:
            qual = 'negligible'
        elif V < 0.21:
            qual = 'small'
        elif V < 0.35:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 3:
        if V < 0.06:
            qual = 'negligible'
        elif V < 0.17:
            qual = 'small'
        elif V < 0.29:
            qual = 'medium'
        else:
            qual = 'large'
    elif df == 4:
        if V < 0.05:
            qual = 'negligible'
        elif V < 0.15:
            qual = 'small'
        elif V < 0.25:
            qual = 'medium'
        else:
            qual = 'large'
    else:
        if V < 0.05:
            qual = 'negligible'
        elif V < 0.13:
            qual = 'small'
        elif V < 0.22:
            qual = 'medium'
        else:
            qual = 'large'
    return(qual)

judgment_CramerV(df,res.loc[2,'results'])

'large'